version: '3.8'

services:
  mcpendpoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcpendpoint
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/database
      - logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SQLITE_PATH=/app/database/wallet-data.db
      - SQLITE_FORCE_BUILD=1
      - npm_config_build_from_source=true
      - npm_config_sqlite_libname=sqlite3
      - YARN_CACHE_FOLDER=/tmp/.yarn-cache
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  db-data:
    driver: local
  logs:
    driver: local 