version: '3.8'

services:
  mcpendpoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcpendpoint
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/database
      - logs:/app/logs
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SQLITE_PATH=/app/database/wallet-data.db
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db-data:
    driver: local
  logs:
    driver: local 